### ISSUE TITLE
Error on 1st step

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#1]
Error:
--  While building package postgresql-libpq-0.9.4.2 using:
      C:\Users\sameb\AppData\Local\Temp\stack17996\postgresql-libpq-0.9.4.2\.stack-work-devel\dist\e626a42b\setup\setup --builddir=.stack-work-devel\dist\e626a42b configure --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\95f3e913\pkgdb --libdir=C:\sr\snapshots\95f3e913\lib --bindir=C:\sr\snapshots\95f3e913\bin --datadir=C:\sr\snapshots\95f3e913\share --libexecdir=C:\sr\snapshots\95f3e913\libexec --sysconfdir=C:\sr\snapshots\95f3e913\etc --docdir=C:\sr\snapshots\95f3e913\doc\postgresql-libpq-0.9.4.2 --htmldir=C:\sr\snapshots\95f3e913\doc\postgresql-libpq-0.9.4.2 --haddockdir=C:\sr\snapshots\95f3e913\doc\postgresql-libpq-0.9.4.2 --dependency=Cabal=Cabal-2.4.1.0-78x0vw3MyCl4xpT30nlxaF --dependency=Win32=Win32-2.6.1.0 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 -f-use-pkg-config --extra-include-dirs=C:\Users\sameb\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\include --extra-lib-dirs=C:\Users\sameb\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\lib --extra-lib-dirs=C:\Users\sameb\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\bin --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

Warning: Build failed, but trying to launch GHCi anyway
The following GHC options are incompatible with GHCi and have not been passed to it: -O2
Configuring GHCi with the following packages: naruto-unison

Warning: Didn't find expected autogen file: D:\naruto-unison\.stack-work-devel\dist\e626a42b\build\autogen\cabal_macros.h
Progress 1/4GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package persistent-postgresql-2.9.1
    (use -v for more information)

got this error during "stack ghci naruto-unison:lib --no-load --work-dir .stack-work-devel" process

**Comment by jnbooth** [comment]
Hmm. Does installing [PostgreSQL](https://www.postgresql.org/download/) fix that? If so, I'll add a note about that.
(By the way, this project is very much a work in progress. I'm not sure how anyone found it!)

**Comment by Kerodas** [comment]
I installed PostgreSQL, but it didn't fix the problem and that's not surprising since its cabal package problem.
(Finding this project was not a problem, got first link on google, while looking for n-a source code, was pretty sure that after some time, someone will try to recreate n-a and I understand that it's work in progress and it makes me curious about it.)

**Comment by jnbooth** [comment]
The problem you're having is with building the [postgresql-libpq](https://github.com/phadej/postgresql-libpq) package rather than anything N-U, so I don't know how helpful I can be, but I'll certainly give it a shot! Try this:

- Close any cmd.exe instances you have open.
- Go to Settings -> Edit environment variables for your account
- Select Variable -> Path and click Edit
- Browse...
- Navigate to the folder in which you installed PostgreSQL, click on the folder named 'bin', and click OK.
- Click OK again to exit the window.
- Open a new cmd.exe and try to run Stack again.

**Comment by jnbooth** [comment]
I've updated the README to include an installation guide.

**Comment by Kerodas** [comment]
Yes, it worked! Thank you for help and thank you for installation guide!
