### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by jnbooth** [naruto-unison/naruto-unison#13]
Every Shippuden and Reanimated character should have a mission that must be completed in order for a player to unlock them.

**Comment by jnbooth** [comment]
None of the missions should depend on XP, Rank, or any other kind of metric. Not one.

If a character exists in both Original and Shippuden, the mission to unlock the Shippuden one should be a simple set of challenges based on using the Original one.

I would like there to be some kind of PvE challenge for certain missions, but that would require making the AI a bit smarter, and I'm not sure yet how it would fit in with everything else.

**Comment by Kerodas** [comment]
You could implement currency that you earn by winning games in any mode which will then allow to unlock certain missions from D, C, B, A and S rank. 

Mission itself could be a boss fight with a preset team that resembles anime events, like for example mission to unlock Sasori will require you to fight with Sakura and Chiyo vs Sasori that transforms each time when his HP reaches 0. 

To make a boss you can make a separate character that is not displayed on the roster.

**Comment by jnbooth** [comment]
Currency is a _very_ interesting idea. It could create fun incentives for players, too, like randomly selecting a handful of characters each day that reward currency for using them as an incentive to mix up your team comps from time to time.

Ah, there we go, the boss fights idea is exactly what I was missing. It would be those variations and passive effects that would make them actual challenges. Another one that comes to mind is a Kabuto who can res his teammates without limits.

**Comment by jnbooth** [comment]
8ba12b1 introduces the mission system, with demo missions for Naruto (S), Sasuke (S), and Sakura (S). Over the next few days, I hope to add missions for the majority of Shippūden characters. This is the idea:

- Original characters have no missions.
- Shippūden characters have missions based on wins, skill use, etc.
- Reanimated characters are purchased with currency, which will be called something like DNA. (Or Souls? That's the other component of the Reanimation technique, but the Dark Souls game already uses Souls as currency, so it might be a bit silly.) Most of them probably have one or two Shippūden-esque objectives as well. Anyway, DNA is rewarded for:
    - Winning a match
    - Losing a match, but not as much
    - Advancing on the competitive ladder
    - Defeating AI boss fights (more on this to come)
    - Participating in wars (more on this to come)
    - Video Game Nonsense (login streaks, first-game-of-the-day bonuses, etc.)

Mission difficulty is going to require a _lot_ of tuning, though. Polls or feedback threads or something. I have no idea how high the goals should  be set to make them entertaining and challenging without feeling unpleasantly grind-y. Furthermore, characters who are Really Cool should probably have higher goals and harder objectives. Unfortunately, this means Yota (S) will never be added to the game, because he is so unbelievably cool that his mission would be impossible by necessity.

**Comment by jnbooth** [comment]
Oh, and I will also have to spend time on polishing and abstraction-plating the mission system. I would like it to be as intuitive and easy to use as the character skills system, and hopefully not much harder to test. It's straightforward and pure, so that should be achievable.

**Comment by jnbooth** [comment]
Note: Mission locking is enabled by editing [config/settings.yml](https://github.com/naruto-unison/naruto-unison/blob/master/config/settings.yml) and uncommenting this line:
```yaml
# unlock-all: false
```
to
```yaml
unlock-all: false
```
By default, `unlock-all` is true in `yesod devel` and false in `yesod keter`.

**Comment by jnbooth** [comment]
A lot of missions still need to be added, but the mission system itself is implemented as of the above commits, so I'm closing this issue. If problems occur with missions, those should be new issues anyway.
