### ISSUE TITLE
Registration doesn't work

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#2]
It says:
INTERNAL SERVER ERROR
/usr/sbin/sendmail: createProcess: does not exist (No such file or directory)
after filling in email and clicking Register button in main menu.
Is there any workaround like a file where all account details are stored?
Also curious about account privilege (Admin, User). Wonder how to change those.

P.S.
How do I change bot's team in practice? I tried editing:

userPractice   = ["Naruto Uzumaki", "Sakura Haruno", "Sasuke Uchiha"]

in src/Handler/Play.hs , but it did nothing

Thank you for further!

**Comment by jnbooth** [comment]
As that error line suggests, Yesod's email registration system uses [sendmail](https://en.wikipedia.org/wiki/Sendmail), which is not available on Windows. According to the [Yesod docs](https://www.yesodweb.com/book/authentication-and-authorization#authentication-and-authorization_email), your other option is to set up an Amazon SES account and use the [mime-mail-ses](https://www.stackage.org/package/mime-mail-ses) package.

Accounts are not stored in a file, but rather (as one might expect) in the SQL database. Tables in a Yesod database are named for the type of data they contain, so the table you're looking for is the one called 'user'.

The practice team is chosen by the client, in [/elm/src/Site/Select.elm](https://github.com/naruto-unison/naruto-unison/blob/master/elm/src/Site/Select.elm), on lines 258-259:
```elm
team = (++) (st.url ++ "api/practicequeue/") << String.join "/"
<| List.map characterName st.team ++ ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno"]
```
 I'm currently working on adding a menu to the website that lets you select which team you want to practice against, along with a checkbox for whether or not the AI should be enabled. Once that's done, the user's selection will replace the currently hardcoded team. (Which will make it much easier for me to test skills out by hand during the process of writing [automated tests](https://github.com/naruto-unison/naruto-unison/blob/master/test/Characters/Original/KidsSpec.hs).)

**Comment by jnbooth** [comment]
As that error line suggests, Yesod's email registration system uses [sendmail](https://en.wikipedia.org/wiki/Sendmail), which is not available on Windows. According to the [Yesod docs](https://www.yesodweb.com/book/authentication-and-authorization#authentication-and-authorization_email), your other option is to set up an [Amazon SES](https://aws.amazon.com/ses/pricing/) account and use the [mime-mail-ses](https://www.stackage.org/package/mime-mail-ses) package.

Accounts are not stored in a file, but rather (as one might expect) in the SQL database. Tables in a Yesod database are named for the type of data they contain, so the table you're looking for is the one called 'user'.

The practice team is chosen by the client, in [/elm/src/Site/Select.elm](https://github.com/naruto-unison/naruto-unison/blob/master/elm/src/Site/Select.elm), on lines 258-259:
```elm
team = (++) (st.url ++ "api/practicequeue/") << String.join "/"
<| List.map characterName st.team ++ ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno"]
```
 I'm currently working on adding a menu to the website that lets you select which team you want to practice against, along with a checkbox for whether or not the AI should be enabled. Once that's done, the user's selection will replace the currently hardcoded team. (Which will make it much easier for me to test skills out by hand during the process of writing [automated tests](https://github.com/naruto-unison/naruto-unison/blob/master/test/Characters/Original/KidsSpec.hs).)

**Comment by Kerodas** [comment]
I see, thank you for the information.
