### ISSUE TITLE
Visual only (cd bug)

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#23]
In char templates the cd is displayed as twice the actual amount. Inside of the game itself it works properly and is displayed properly, only wrong in char/skill descriptions
This began after the updates from today/yesterday. Before that it worked properly.

and another visual bug- from my brother's pc when he enters it, he can only see the top 2 chars when in game. the 3rd char is out of the screen and he can't scroll to it

**Comment by jnbooth** [comment]
The second issue should be covered by #26.
