### ISSUE TITLE
Percentage damage reduction

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#24]
When a piercing skill is used on a char with % DR, any skill after that ignores the damage reduction( that if withing the same turn) meaning if you use a piercing skill, then one or two normal damage skills, they will act like piercing. On the next turn if you use a non piercing skill it will act normally, unless again you use a piercing skill before it in the same turn
And it seems like the Weaken effects apply after the damage is reduced by Percentage damage reduction

**Comment by jnbooth** [comment]
This isn't a bug report, it's just a description. Try following this format:

**Expected behavior:** When I <X>, <Y> should <Z1>.
**Actual behavior:** When I <X>, <Y> instead <Z2>.

**Comment by jnbooth** [comment]
This isn't a bug report, it's just a description. Try following this format:

**Expected behavior:** When I \<X\>, \<Y\> should \<Z1\>.
**Actual behavior:** When I \<X\>, \<Y\> instead \<Z2\>.

**Comment by RadoUzee** [comment]
When i use damage reduction ( created Nii with infinite 50% DR ) And then when i interact with it:
First error with %  DR 1)
Expected behavior: When I use a skill that deals 20 piercing, then a skill that deals 20 damage, the person with damage reduction should take 20 from the piercing and 10 form the ordinary damage. Total of 30 damage lost.
Actual behavior: When I use a skill that deals 20 piercing, then a skill that deals 20 damage, the person with damage reduction takes 20 from the piercing and 20 form the ordinary damage. Total of 40 damage lost.
As a whole it seems like once damaged by piercing, the DR is disabled until the end of the turn. This works properly if you shift the order of the piercing and normal damage skill ( 1st use normal damage, then piercing and the expected outcome is the same as the actual behavior)
2nd Part of % DR errors
taking again Nii , with his 50% damage reduction
he uses his 30 damage and weaken 10 on an enemy
Expected behavior: The weakened enemy uses a skill that deals 30 damage. It is reduced by 10 so it's 20 for the turn and since it's used on Nii, it should in the end deal 10 damage to Nii
Actual behavior: The weakened enemy uses a skill that deals 30 damage. The % DR triggers first, making the skill deal 15 damage, but is then weakened and falls to 5 damage to Nii

**Comment by jnbooth** [comment]
I've reordered the combat formula so '2nd Part' should be fixed now, but I'll be keeping an eye on damage calculations just in case anything else is out of order. As for 'First error', I haven't been able to replicate that. Do you have the same issue with any character in this repository, such as Maki? It isn't helpful for you to submit a bug report about code (such as Nii) that isn't actually in this repository.

**Comment by RadoUzee** [comment]
It seems like the first error was my mistake, now that i look back on the testing i had a char that had expose as an effect added to the piercing. 
and i'm not sure where exactly to post this part but( in case you want Nii coded to do what he did in original n-a):
Character
    "Nii Yugito"
    "A kunoichi from Kumogakure, Nii Yugito holds within her the two-tailed beast. She has full control over the bijuu Nibi, and is able to transform into it and use its powers to fight. Original Design: lder"
    [ [ Skill.new
        { Skill.name      = "Nibi Transformation"
        , Skill.desc      = "Yugito unlocks the power of her bijuu and takes on its form. She gains 50% damage reduction and can use both Spectral Fireball and Claw Swipe. This skill is permanent and cannot be used while in effect."
        ,Skill.require   = HasI (-1) "Nibi Transformation"
        , Skill.classes   = [Chakra]
        , Skill.cost      = []
        , Skill.effects   =
          [ To Self $ apply 0 [Reduce All Percent 50]
          ]
        }
      ]
    , [ Skill.new
        { Skill.name      = "Spectral Fireball"
        , Skill.desc      = "By spitting a large fireball from her mouth, Yugito deals 30 damage to one enemy. That enemy will deal 10 less non-affliction damage for 1 turn. Each time this skill is used it will deal 5 more damage (this effect stacks)."
        ,Skill.require    = HasI 1 "Nibi Transformation"
        , Skill.classes   = [Chakra]
        , Skill.cost      = [Blood,Rand]
        , Skill.cooldown  = 1
        , Skill.effects   =
          [ To Enemy do
                    stacks <- userStacks "Spectral Fireball"
                    damage (30+5 * (stacks))
                    apply 1 [Weaken NonAffliction Flat 10]
           ,To Self $ apply' "Spectral Fireball" 0 [Strengthen All Flat 0]
          ]
        }
      ]
    , [ Skill.new
        { Skill.name      = "Claw Swipe"
        , Skill.desc      = "Yugito takes a huge swipe of her claw dealing 15 damage to one enemy and 5 damage to all other enemies. This skill will deal 5 more damage each use (this effect stacks)."
        ,Skill.require    = HasI 1 "Nibi Transformation"
        , Skill.classes   = [Physical]
        , Skill.cost      = [Blood]
        , Skill.cooldown  = 1
        , Skill.effects   =
          [ To Enemy do
                    stacks <- userStacks "Claw Swipe"
                    damage (15+5 * (stacks))
           ,To XEnemies do
                       stacks <- userStacks "Claw Swipe"
                       damage (5+5 * (stacks))
           ,To Self $ apply' "Claw Swipe" 0 [Strengthen All Flat 0]
          ]
        }
      ]
    , [ invuln "Rage" "Nii" [Chakra]]
    ] []
(the reason why i use strengthen 0 is because it works best to keep track of stacks. ( if you actually write strengthen 5 it doesn't stack so i use the stacks mechanic) It might be improperly made, but i still haven't read up on the code for all chars.

**Comment by jnbooth** [comment]
I'm not going to say this again: like any other open-source project, **this issues page is for issues regarding the code in the repository.** If you want to fork this project into your own private instance instead of contributing to the repository, forgoing the benefits of collaboration in favor of delivering a half-baked, unfinished product that you yourself do not know how to improve, that's fine. It's your prerogative. But I'm not going to walk you through how to do it step by step.
