### ISSUE TITLE
Targetability and stuns

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#25]
The turn after someone becomes invulnerable:
Expected outcome: they are now targetable
Actual outcome: They are still untargetable for one turn

One turn after a stun ends:
Expected outcome: they are now able to use skills
Actual outcome: They are unable to use skills that were stunned the turn prior.

(while on the turn of the stun they can use the skill, but it won't trigger)

**Comment by jnbooth** [comment]
Should be fixed now, but let me know if it's still having problems.
