### ISSUE TITLE
error during stack build #question

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#27]
I don't know if it's related to project or it's the problem on my end, but I've got an error during compilation of a latest build.

D:\naruto-unison>stack build
Cloning 2e0a888f49316f24526fbbf9ad50fdfab6c197ab from https://github.com/jnbooth/bounded-enum-set.git
Executable named git not found on path: [".","C:\\sr\\snapshots\\21d576af\\bin","C:\\sr\\compiler-tools\\x86_64-windows\\ghc-8.6.5\\bin","C:\\Users\\sameb\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.6.5\\bin","C:\\Users\\sameb\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.6.5\\mingw\\bin","C:\\Users\\sameb\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\mingw64\\bin","C:\\Users\\sameb\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\usr\\bin","C:\\Users\\sameb\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\usr\\local\\bin","C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath","C:\\ProgramData\\Oracle\\Java\\javapath","C:\\Program Files\\Haskell\\bin","D:\\Haskell\\8.6.5\\lib\\extralibs\\bin","D:\\Haskell\\8.6.5\\bin","C:\\Windows\\system32","C:\\Windows","C:\\Windows\\System32\\Wbem","C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\","C:\\Windows\\System32\\OpenSSH\\","C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common","C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR","D:\\Haskell\\8.6.5\\mingw\\bin","C:\\Program Files\\nodejs\\","C:\\Users\\sameb\\AppData\\Roaming\\local\\bin","C:\\Users\\sameb\\AppData\\Roaming\\cabal\\bin","C:\\Users\\sameb\\AppData\\Local\\Microsoft\\WindowsApps","D:\\PostgreSQL\\bin","C:\\Users\\sameb\\AppData\\Roaming\\npm"]

Thank you for attention

**Comment by jnbooth** [comment]
Oh! Yes, you'll need [Git](https://git-scm.com/downloads). I didn't think to make a note of that because this is a GitHub repository, so I assumed people would already have Git. I have added a note about that to the Readme. Sorry about that.

**Comment by Kerodas** [comment]
No need for apologies, everything is cool, thank you!
