### ISSUE TITLE
Ibiki Morino bugs

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#29]
1. Ibiki Morino 's first skill does not get changed after use. 
Expected outcome: It becomes Payback
Actual outcome: It stays the same and can be used again but it pretty much doesn't do anything, even though it gives a 2nd stack of it ( because reduce all flat 10 doesn't stack )
I have no idea why, as it seems that the vary is written the same way that ino and gaara's vary work. And i checked those two and it works for them.

2. Ibiki Morino 's second skill counts on going skills as seperate ones each turn:
Ibiki uses his 2nd skill on ino. Ino then uses her continuos stun skill, takes 25 damage. Next turn she uses her first skill, and takes 50 damage.
The expected outcome would be taking only 25 damage on the 2nd turn and not 50.

3. Ibiki Morino 's third skill applies 25 initial damage to the target and deals 50 damage each turn if they use a skill and 25 if they don't
the expected outcome would be for it to not deal any damage initially and for it to deal 25 damage to the enemy when they don't use any skill

Edit: Update: If the third skill is used on turn 1 before the enemy has had a turn, they won't take the initial 25 damage and they will take 25 if they don't use a skill, but 50 if they do use a skill.

Side issue: Gaara's Sand Clone does not prevent Ibiki's trap skills

**Comment by jnbooth** [comment]
Those should all be fixed now, with the exception of Gaara. At present, Gaara's Sand Clone only blocks status effects, not traps. Should it be otherwise? I don't remember.

**Comment by RadoUzee** [comment]
> Those should all be fixed now, with the exception of Gaara. At present, Gaara's Sand Clone only blocks status effects, not traps. Should it be otherwise? I don't remember.

well in the original there was f.e.:
Gaara uses sandclone, neji uses his 2 turn 25 damage, sand clone removes neji's skill after he takes 25 damage so he prety much doesn't have the 2nd turn effect. But tbh that's a bit confusing and complex so your version might be better.
