### ISSUE TITLE
Bug on Removing Chakra

### ISSUE THREAD

**Issue by YanAlexandreJr** [naruto-unison/naruto-unison#38]
The bug i had while i was playing is: If you remove ur opponent chakra and he has used all of his chakra before, he wont lose his chakra. I mean, you can only lose chakra if that chakra is what u have saved before. If u spended 2 chakras out of 3, then ur opponent removes 2 chakras of u, u'll only lose one chakra, and that chakra is the same which u have saved.
First of all, sorry for my bad english :v

Screenshots:
https://i.imgur.com/Ja3dGUf.png <<< Using all of my chakra
https://i.imgur.com/U6YmP7x.png <<< Now i have no removed chakra.
I hope i help u with that xD

Btw, i have a request to make to you:
I dont know if its just because its not an official version, but could u make the user of the first turn begins with only one chakra?

Ty

**Comment by jnbooth** [comment]
Ah, no, that was just my poor memory. Both of those should be fixed now. Let me know if they aren't, though! Thank you for pointing this out.
