### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#39]
src\Handler\Play\Rating.hs:65:22-31: error:
    * Data constructor not in scope: UserRecord :: EntityField User Int
    * Perhaps you meant variable `Sql.insertRecord' (imported from Database.Persist.Sql)
   |
65 |         ESQL.set p [ UserRecord ESQL.=. p ^. UserStreak ]
   |                      ^^^^^^^^^^

src\Handler\Play\Rating.hs:67:47-56: error:
    * Data constructor not in scope: UserRecord :: EntityField User Int
    * Perhaps you meant variable `Sql.insertRecord' (imported from Database.Persist.Sql)
   |
67 |         ESQL.where_ $ p ^. UserStreak >. p ^. UserRecord
   |                                               ^^^^^^^^^^

--  While building package naruto-unison-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe --builddir=.stack-work\dist\e626a42b build lib:naruto-unison exe:elm-bridge exe:naruto-unison --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

**Comment by jnbooth** [comment]
If you run `stack clean` and then rebuild, does the problem still occur? The UserRecord constructor is produced by Template Haskell, so maybe something was cached improperly.

**Comment by Kerodas** [comment]
the same problem even after stack clean

**Comment by jnbooth** [comment]
Hmm. In your SQL database, does the "user" table have a "record" field?

**Comment by jnbooth** [comment]
I've added the DNA field to the User type to hopefully give your Template Haskell persistence a kick in the pants. It would have been added in eventually anyway.

**Comment by jnbooth** [comment]
Did this resolve the issue?

**Comment by Kerodas** [comment]
Yes, issue is resolved. Thank you!

**Comment by jnbooth** [comment]
Sweet.
