### ISSUE TITLE
Problem starting it up

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#42]
It's been a while since i tried to start it up, i got the latest version and did what i normally do, but i get this error https://imgur.com/9gipdga. For me registering an account gives an error, so when testing stuff i normally just use dummy login and been using the same name multiple times(probably my error is coming from this). I was wondering if i need to do something more on the database to make it work? Since whenever i try to start up an older version that worked i get this message now: https://imgur.com/Gh6pQ0i . Hoping to catch up with all the updates you've made.

Sadly I currently have no knowledge of working with a databases.

**Comment by jnbooth** [comment]
I added a case-insensitive constraint to usernames because if someone has the username "Crimson," another user should not be allowed to register the username "crimson," which appears to be what you have done. The problem should be fixed if you delete one of those users from the "user" table.

**Comment by RadoUzee** [comment]
I have no experience with databases, so sorry if this question is annoying: How do i find the logins from dummy login inside of the database? All i found is this place https://imgur.com/4GtsOuR
whenever i try to click on the id etc. nothing happens.

**Comment by jnbooth** [comment]
In the sidebar on the left, under "Tables", right click on "user", then "View/Edit Data" -> "All Rows". You might find the [pgAdmin 4 documentation[(https://www.pgadmin.org/docs/pgadmin4/latest/index.html) helpful.

**Comment by RadoUzee** [comment]
Thanks a lot, now it's working !
