### ISSUE TITLE
Awakening skill idea

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#49]
I've got an idea about special skills for players. 
You can add a bar with 0/100 that will fill during the match. The bar will fill based on damage taken by your characters with inclusion of destructible defense and damage reduction in match divided by 2. 
So basically when your team gets damaged by 200, you get a chance to use awakening skill which should help you to even odds against a stronger opponent. 
For example, those could be defensive skills like "additional dd or healing of the whole team for a certain amount of turns", it could be a damaging skill which deals like "10 affliction damage for 3 turns to all enemy team ignoring invulnerability", or even match affecting skills, like "skip your opponent's turn" or "disable 3 skills of your opponent, 1 skill per character for 3 turns".
You could give player a choice between 2 random awakening skills each week, which should give more variety for teams and this will also affect meta teams for pvp to the point, where they won't last long. Otherwise they can be awarded for achieving certain rank or even purchased with currency.

**Comment by jnbooth** [comment]
Neat idea! Definitely open a pull request for it once you've implemented it.
