### ISSUE TITLE
Register and Login

### ISSUE THREAD

**Issue by robertvlasiu** [naruto-unison/naruto-unison#52]
Hi,
What route do you get in the email following the registration?
I want to test the login and register but my server is on a Windows so I don't have the SendMail. I figured that you might have to put that "verkey" in a url to get prompted to insert a password but I don't know what route would that be. 

Thank you!

**Comment by jnbooth** [comment]
It's a little more complicated, but you don't need to worry about that. If you pull the commit I just pushed and register a user, the verification URL will be printed directly to the console/log, prefixed by "VERIFICATION URL:"

The mailing system is definitely the project's weakest link, and the main thing holding back the Dockerfile. Maybe it would be better to use a plain SMTP Haskell-native library? Although that would presumably require storing credentials in environment variables. In the meantime, the latest commit should work as a stopgap for you.

**Comment by robertvlasiu** [comment]
Hi, 
Thank you very much for your help! I know it was a basic thing to do, but Haskell is giving me a hard time, not being used with functional programming so sorry for the noobie request.  There is this service called SendGrid which has an API which you can call and they send your mail. Problem is, for the free package you can only send 100 emails per month, but they have a good reputation and rarely end in Spam. 

I don't really know at the moment if Haskell has the Service concept, but if it does have it or something similar you could create a Mailer Service with some constants that handle the mail sending, so you don't share your credentials between all files.

Thank you again for your help!

**Comment by jnbooth** [comment]
Interesting. It looks like SendGrid even has a [Haskell library](https://hackage.haskell.org/package/sendgrid-v3). I will definitely look into this!

Haskell is weird and so is this project, so feel free to email me if you have any questions about how the code fits together. Things have stalled because I have neither the time nor the funds to commit to an actual site launch, but I'm still around.
