### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [naruto-unison/naruto-unison#56]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by brunolnetto** [comment]
Hi @codehangen. There is a thread post on reddit about this game: https://www.reddit.com/r/NarutoArena/comments/gtkhtu/narutoarena_github_contributors/

The current repository is not official.

**Comment by ghost** [comment]
Hi brunolnetto.

> Hi @codehangen. There is a thread post on reddit about this game: https://www.reddit.com/r/NarutoArena/comments/gtkhtu/narutoarena_github_contributors/
> The current repository is not official.

thank you for comment.
