### ISSUE TITLE
More stuff for fixing

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#6]
If you don't want me posting these, just inform me, only hoping to make it easier on you:
1) Hanabi's first skill doesn't work with chakra absorb
2) Shizune's affliction skill can kill hanabi during her Immortality skill also anko's dragon flame also her striking  shadow snakes.
^the patern seems to point that instant skills that deal affliction damage can go past Endure mechanic. 
3)Kin's Bell Ring Illusion only gives a tag when you have used it after Shadow senbon so i fixed it to:
[ p Self $ whenM (userHas "Shadow Senbon") $ apply 1 [Invulnerable All]
           ,p Self $ tag 1
           ,p Enemy do
                bonus <- 25 `bonusIf` userHas "Unnerving Bells"
                damage (15 + bonus)
          ]

4) Kabuto's chakra increasing effect doesn't seem to work. Instead it works as a full stun
Kabuto's 3rd skill, makes it so the enemies are all stunned and if they use a skill, they are stunned again. Which is different from the text of the skill
i tried fixing it but failed:
[ Skill.new
        { Skill.name      = "Temple of Nirvana"
        , Skill.desc      = "Illusory white feathers descend upon the battlefield and lull the enemy team to sleep. Unless an enemy uses a skill next turn, they will be stunned for 1 turn and receive 10 additional damage from physical and chakra skills."
        , Skill.classes   = [Mental, Ranged]
        , Skill.cost      = k [Gen]
        , Skill.cooldown  = 2
		, Skill.channel   = Ongoing 2
		, Skill.start     =
          [ p Self $ tag' "Has this used"]
        , Skill.effects   =
          [ p Enemies $ whenM(userHas  trap (-1) OnNoAction $ tag' "Trapped in an illusion" 1
           ,p Enemies whenM (targetHas "Trapped in an illusion") do
  		                apply 1 [ Stun All
                        , Bleed Physical Flat 10
                        , Bleed Chakra Flat 10
                        ]
          ]
        }
i was thinking of doing something like this and then add a remove "Has this used" once the skill ends, but i got too many errors so i gave up on the idea
5)i'm not sure if this was intended, but his 5 turn heal cures Bane skills each turn.

6) Misumi's reflect doesn't work

7)For some reason if i click to use oboro's Exploding Kunai before clicking on a 1 chakra skill ( when you have 3 chakra) it doesn't let you pick the 1 chakra skill. happened to me with zaku in team
as a whole oboro seems to be having a hard time to use his exploding kunai .

9)Yoroi damage buff doesn't work  /  damage reduction doesn't work on yoroi
^ seems like the leech mechanic isn't working properly with damage buff/weaken

another overall problem: You can't chakra exchange when you have only 5 chakra

-----------------------------------more stuff added----------------------------------------------
1) Kakashi's sharingan cost is tai and nin / should be blood  ( but the good news is that the reflect works)
2) Mizuki's giant shuriken text says deals 10 initial damage, but is coded as 20
3) Kurenai has the same issue as kabuto when increasing chakra cost. I can't seem to find the patern of how it ends up working isntead. 
4) When a skill is countered, the target regains the chakra used for the skill
5) When an AoE skill is countered, the counter only prevents the counterer from losing damage

as a whole it seems that traps don't work against aoe skills

**Comment by jnbooth** [comment]
I'm going to split these up into separate issues.

**Comment by jnbooth** [comment]
#8, #9, and #10 cover the aspects of this issue that do not pertain to specific character implementations.

**Comment by jnbooth** [comment]
All right. I _think_ these should all be fixed now. I'm not 100% confident because a) there isn't a character testing suite yet, unfortunately, and b) there have been a lot of changes in the past month due to implementing an actual counter system, etc. So I will be keeping an eye on this, and definitely bring it up if you see any inconsistencies.
